### ISSUE TITLE
ifort error

### ISSUE THREAD

**Issue by rolfmertig** [jchristopherson/ferror#6]
If I try with the latest ifort compiler on Linux 
`ifort -c ferror.f90 ferror_implementation.f90`  , 
I get a few warnings about gnu extensions idate and itime (which probably could get fixed by adding `use ifport` in ferror.f90) ,
and an error 
```

ferror_implementation.f90(274): error #6122: The characteristics of the separate module procedure differ from those specified in the separate interface body.   [ER_GET_ERR_FCN_PTR]
module function er_get_err_fcn_ptr(this) result(ptr)
compilation aborted for ferror_implementation.f90 (code 1)

```
I would really like to be able to use ferror, in linalg, with ifort (and ifx). 
However, I cannot get it to work.
If it helps, I asked chat.openai.com about error #6122 and this is its answer, which still does not
help me enough to fix the problem myself.

This error message is generated by the Intel Fortran compiler (ifort) and indicates that there is a mismatch between the characteristics of a procedure defined in a module and those specified in the separate interface body for that procedure.

There are several possible reasons for this error:

1.     The procedure may have been defined with different arguments or a different return type in the module than those specified in the separate interface body.
2.     The procedure may have been defined with different accessibility (e.g. public, private) in the module than that specified in the separate interface body.
3.     There may be a typo or other mistake in the name of the procedure in the separate interface body.

To fix this error, you will need to ensure that the procedure is defined consistently in the module and in the separate interface body. This may involve modifying the procedure definition or the separate interface body to match the other.

**Comment by jchristopherson** [comment]
Hi @rolfmertig.  I do not use ifort on Linux.  I will investigate, and I will update this thread once I'm able to figure out a solution.  My recommendation in the meantime is to create a fork and work the issue from your side.  If you're able to figure out something, please send me a pull request so I may review.

**Comment by jchristopherson** [comment]
Hi @rolfmertig.  I have found a fix.  I'm in process of implementing, and once I have everything updated, I will let you know.

**Comment by jchristopherson** [comment]
Hi @rolfmertig.  Everything should be good to go.  Please give it a try and let me know if you have any issues.  I'll close this issue once I hear back that you were successful.

**Comment by jchristopherson** [comment]
I'm closing this issue as everything appears to be working.
